from django.db import models
from django.utils import timezone
from apps.users.models import User
from apps.core.models import Department, ProjectStatus, ProjectPhase, ProjectPriority, ProbabilityLevel, ImpactLevel, SeverityLevel, ChangeDecisionStatus
class TimestampedModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta: abstract = True
class Project(TimestampedModel):
    project_code=models.CharField(max_length=50, unique=True)
    project_name_ar=models.CharField(max_length=300)
    description=models.TextField(blank=True)
    owning_department=models.ForeignKey(Department,on_delete=models.PROTECT,related_name="projects")
    status=models.ForeignKey(ProjectStatus,on_delete=models.PROTECT,related_name="projects")
    phase=models.ForeignKey(ProjectPhase,on_delete=models.PROTECT,related_name="projects")
    priority=models.ForeignKey(ProjectPriority,on_delete=models.PROTECT,related_name="projects")
    sponsor=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="sponsored_projects")
    owner=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="owned_projects")
    manager=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="managed_projects")
    planned_start_date=models.DateField(null=True,blank=True)
    planned_end_date=models.DateField(null=True,blank=True)
    actual_start_date=models.DateField(null=True,blank=True)
    actual_end_date=models.DateField(null=True,blank=True)
    completion_percentage=models.DecimalField(max_digits=5, decimal_places=2, default=0)
    overall_score=models.DecimalField(max_digits=5, decimal_places=2, default=0)
    baseline_exists=models.BooleanField(default=False)
    is_draft=models.BooleanField(default=True)
    is_active=models.BooleanField(default=True)
class ProjectBudget(TimestampedModel):
    project=models.ForeignKey(Project,on_delete=models.CASCADE,related_name="budgets")
    budget_version=models.PositiveIntegerField(default=1)
    planned_budget_amount=models.DecimalField(max_digits=18, decimal_places=2, default=0)
    approved_budget_amount=models.DecimalField(max_digits=18, decimal_places=2, default=0)
    contract_value=models.DecimalField(max_digits=18, decimal_places=2, default=0)
    spent_amount=models.DecimalField(max_digits=18, decimal_places=2, default=0)
class ProjectRisk(TimestampedModel):
    project=models.ForeignKey(Project,on_delete=models.CASCADE,related_name="risks")
    risk_code=models.CharField(max_length=50, unique=True)
    title=models.CharField(max_length=250)
    description=models.TextField(blank=True)
    probability=models.ForeignKey(ProbabilityLevel,on_delete=models.PROTECT,related_name="risks")
    impact=models.ForeignKey(ImpactLevel,on_delete=models.PROTECT,related_name="risks")
    severity=models.ForeignKey(SeverityLevel,on_delete=models.PROTECT,related_name="risks")
    owner=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="risks")
    mitigation_plan=models.TextField(blank=True)
    target_closure_date=models.DateField(null=True,blank=True)
    status=models.ForeignKey(ProjectStatus,on_delete=models.PROTECT,related_name="risk_statuses")
    ai_generated_flag=models.BooleanField(default=False)
class ProjectIssue(TimestampedModel):
    project=models.ForeignKey(Project,on_delete=models.CASCADE,related_name="issues")
    issue_code=models.CharField(max_length=50, unique=True)
    title=models.CharField(max_length=250)
    description=models.TextField(blank=True)
    severity=models.ForeignKey(SeverityLevel,on_delete=models.PROTECT,related_name="issues")
    owner=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="issues")
    resolution_plan=models.TextField(blank=True)
    target_resolution_date=models.DateField(null=True,blank=True)
    status=models.ForeignKey(ProjectStatus,on_delete=models.PROTECT,related_name="issue_statuses")
class ProjectChangeRequest(TimestampedModel):
    project=models.ForeignKey(Project,on_delete=models.CASCADE,related_name="change_requests")
    cr_number=models.CharField(max_length=50, unique=True)
    title=models.CharField(max_length=250)
    description=models.TextField(blank=True)
    requested_by=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name="requested_changes")
    business_justification=models.TextField(blank=True)
    impact_on_cost=models.DecimalField(max_digits=18, decimal_places=2, default=0)
    impact_on_schedule_days=models.IntegerField(default=0)
    decision_status=models.ForeignKey(ChangeDecisionStatus,on_delete=models.PROTECT,related_name="change_requests")
